# Generated by Django 4.2rc1 on 2023-03-31 14:19

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Humidity",
            fields=[
                ("id", models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ("indication", models.CharField(max_length=255)),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Влажность",
            },
        ),
        migrations.CreateModel(
            name="HydrogenIndicator",
            fields=[
                ("id", models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ("indication", models.CharField(max_length=255)),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "pH",
            },
        ),
        migrations.CreateModel(
            name="Illumination",
            fields=[
                ("id", models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ("indication", models.CharField(max_length=255)),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Освещение",
            },
        ),
        migrations.CreateModel(
            name="SolutionConductivity",
            fields=[
                ("id", models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ("indication", models.CharField(max_length=255)),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Проводимость раствора",
            },
        ),
        migrations.CreateModel(
            name="Temperature",
            fields=[
                ("id", models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ("indication", models.CharField(max_length=255)),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Температура",
            },
        ),
    ]
