# Generated by Django 4.2 on 2023-05-07 09:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_climate_climateschedule_climatestate_light_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Irrigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField(verbose_name='мощность')),
            ],
            options={
                'verbose_name': 'Manual.Полив',
                'verbose_name_plural': 'Manual.Полив',
            },
        ),
        migrations.CreateModel(
            name='IrrigationSchedule',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time_start', models.CharField(verbose_name='начало расписания')),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='продолжительность')),
                ('power', models.IntegerField(verbose_name='мощность')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('taken', models.BooleanField(default=False, verbose_name='расписание зафиксировано')),
            ],
            options={
                'verbose_name': 'Schedule.Полив',
                'verbose_name_plural': 'Schedule.Полив',
            },
        ),
        migrations.CreateModel(
            name='IrrigationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('авто', 'Auto'), ('ручной', 'Manual'), ('выключено', 'Off')], verbose_name='тип работы')),
            ],
            options={
                'verbose_name': 'State.Полив',
                'verbose_name_plural': 'State.Полив',
            },
        ),
        migrations.AlterModelOptions(
            name='climate',
            options={'verbose_name': 'Manual.Микроклимат', 'verbose_name_plural': 'Manual.Микроклимат'},
        ),
        migrations.AlterModelOptions(
            name='climateschedule',
            options={'verbose_name': 'Schedule.Микроклимат', 'verbose_name_plural': 'Schedule.Микроклимат'},
        ),
        migrations.AlterModelOptions(
            name='climatestate',
            options={'verbose_name': 'State.Микроклимат', 'verbose_name_plural': 'State.Микроклимат'},
        ),
        migrations.AlterModelOptions(
            name='humidity',
            options={'verbose_name': 'ind.Влажность', 'verbose_name_plural': 'ind.Влажность'},
        ),
        migrations.AlterModelOptions(
            name='hydrogenindicator',
            options={'verbose_name': 'ind.pH', 'verbose_name_plural': 'ind.pH'},
        ),
        migrations.AlterModelOptions(
            name='illumination',
            options={'verbose_name': 'ind.Освещение', 'verbose_name_plural': 'ind.Освещение'},
        ),
        migrations.AlterModelOptions(
            name='light',
            options={'verbose_name': 'Manual.Освещение', 'verbose_name_plural': 'Manual.Освещение'},
        ),
        migrations.AlterModelOptions(
            name='lightschedule',
            options={'verbose_name': 'Schedule.Освещение', 'verbose_name_plural': 'Schedule.Освещение'},
        ),
        migrations.AlterModelOptions(
            name='lightstate',
            options={'verbose_name': 'State.Освещение', 'verbose_name_plural': 'State.Освещение'},
        ),
        migrations.AlterModelOptions(
            name='solutionconductivity',
            options={'verbose_name': 'ind.Проводимость раствора', 'verbose_name_plural': 'ind.Проводимость раствора'},
        ),
        migrations.AlterModelOptions(
            name='temperature',
            options={'verbose_name': 'ind.Температура', 'verbose_name_plural': 'ind.Температура'},
        ),
    ]
