# Generated by Django 4.2 on 2023-05-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_reedsensor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climateschedule',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='climateschedule',
            name='taken',
        ),
        migrations.RemoveField(
            model_name='irrigationschedule',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='irrigationschedule',
            name='taken',
        ),
        migrations.RemoveField(
            model_name='light',
            name='brightness',
        ),
        migrations.RemoveField(
            model_name='lightschedule',
            name='brightness',
        ),
        migrations.RemoveField(
            model_name='lightschedule',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='lightschedule',
            name='taken',
        ),
    ]
