# Generated by Django 4.2.1 on 2024-06-19 06:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cameraimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('indication', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ind.Резистивный датчик влажности',
                'verbose_name_plural': 'ind.Резистивный датчик влажности',
            },
        ),
    ]
