version: "3.8"

services:
  app:
    container_name: ${APP_CONTAINER_NAME}
    ports:
      - ${SERVER_PORT}:8000
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
