version: "3.8"

services:
  db:
    container_name: raspberry_db
    image: postgres:14.5-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - raspberry_db_volume:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"

volumes:
  raspberry_db_volume: